kiegroup/optaplanner-website

download/download.adoc

For reference: http://www.grammarbook.com/punctuation/apostro.asp

Removed Apostrophes where unnecessary,

---

download/releaseNotes/releaseNotes6.3.adoc

Not sure if you want to add this to the release notes (or if it doesn't make sense), feel free to reject it.

PLANNER-360: Added BigIntegerValueRange to release notes

---

download/releaseNotes/releaseNotes6.3.adoc

Merge only after PLANNER-284 is fixed.

PLANNER-284: Release notes mention

---

localized/de/index.adoc

* Remember to enable the German localization (flag)
* Needs checking by someone who actually knows German :)

Added German localization

---

README.adoc

"ERROR: README.adoc: line 3: only book docctypes can contain level 0 sections"

Fix asciidoctor complaints in README

---

_config/pom.yml

this PR has to be merged in before we can publish the website

updated to 6.4.0.Beta1

---

localized/ja/UserGuide-chapter1.adoc

Hi Geoffrey,
Huge apologies for the delay! Here is the Chapter 1 Japanese translation by Ishii-san.
Thanks!

Chapter 1 translation by Takugo Ishii

---

_config/pom.yml
download/download.adoc

@ge0ffrey pls review this. in case it is OK please publish it.

upgraded to 6.5.0.Final

---

README.adoc

This PR (commit) can be reverted.
This PR is to verify if the Jenkins Job that publishes the optaplanner-website in a Docker container is triggered after this PR was merged.

Please merge this, it only modifies the Readme

---

community/product.adoc

Noticed some links point to urls where user gets lost, updated those.

Update RH links in product.adoc

---

_config/pom.yml
download/download.html.haml
learn/documentation.adoc

@ge0ffrey download.adoc shouldn't be added again - sorry

upgraded to 7.0.0.Final

---

download/download.html.haml
website/optaplannerWebsite.css

PLANNER-821: Website: Downloads page: Replace pills by tabs

---

learn/slides/optaplanner-presentation/training.html

Download and Run examples paragraph has moved to 1.5 in new documenta…

Fixes reference to "Download and Run Examples"

---

blog/2017-08-18-OptimizeYourProblemsUsingKieServerPart.adoc

@ge0ffrey Mind publishing this? The part 2 will provide a description of setting up a real-time planning on the KIE Server.

PLANNER-832: Write a blog post about OptaPlanner Workbench xor Execution Server

---

_config/users.yml

Your probably want to edit the commit message; I think you can change it directly on GitHub by picking "squash and merge" or "rebase and merge" when merging (that actually how I changed mine, but I forgot to remove the header)

Added @Christopher-Chianelli as a contributor

---

_dockerPublisher/Dockerfile

Update fed rub

---

_dockerPublisher/Dockerfile

added missing dependencies to do rake publish

---

_config/pom.yml
download/download.html.haml

feel free to merge when it is green - it gets automatically published

upgrade to 7.7.0.Final

---

_dockerPublisher/Dockerfile

when this is "online" and works I will do the same PRs for drools and jbpm

Added awestruct

---

blog/2019-01-17-HowMuchFasterIsJava11.adoc

more compact writing, remove "could"s etc, use "the" and "a" were needed

Blog suggestions

---

download/download.html.haml

Due to https://stackoverflow.com/questions/55717865/optaplanner-dependencies-via-gradle-within-intellij-idea

Gradle docs

---

learn/rhpds/index.adoc
learn/rhpds/optaweb-employee-rostering.adoc
learn/rhpds/optaweb-vehicle-routing.adoc
learn/useCases/vehicleRoutingProblem.adoc

@yurloc Please link the https://www.optaplanner.org/learn/rhpds/optaweb-vehicle-routing.html url from your description.

First pages for RHPDS instructions

---

_config/references.yml
blog/2013-10-11-WillSkynetControlOurSchedule.adoc
blog/2014-04-17-PutTheUserInControlOfTheScoreConstraints.adoc
blog/2015-05-19-OptaPlannerOnAndroid.adoc
blog/2015-10-01-SneakPeekAtOptaPlannerWorkbench.adoc
blog/2015-12-01-TimeSchedulingDesignPatterns.adoc
blog/2017-08-18-OptimizeYourProblemsUsingKieServerPart.adoc
blog/2018-02-19-SchedulingVoxxedDaysZurich2018.adoc
blog/2018-05-23-BehindTheScenesOfRedHatSummitScheduling.adoc
blog/2018-08-21-UnitTestingConstraintsWithBusinessInputFromExcelOrLibreOffice.adoc
blog/2019-05-09-RHSummit2019Part1.adoc
blog/2019-05-09-RHSummit2019Part2.adoc
blog/2019-05-09-RHSummit2019Part3.adoc
download/releaseNotes/releaseNotes6.4.adoc
download/releaseNotes/releaseNotes7.adoc
index.html.haml
learn/rhpds/optaweb-employee-rostering.adoc
learn/useCases/cloudOptimization.adoc
learn/useCases/conferenceScheduling.adoc
learn/useCases/employeeRostering.adoc
learn/useCases/index.html.haml
learn/useCases/maintenanceScheduling.adoc
learn/useCases/taskAssignmentOptimization.adoc
learn/useCases/vehicleRoutingProblem.adoc
learn/video.adoc
website/optaplannerWebsite.css

Make website more mobile friendly (SEO advantage) + add maintenance scheduling landing page

---

blog/2013-10-11-WillSkynetControlOurSchedule.adoc
blog/2014-03-27-IsTheSearchSpaceOfAnOptimizationProblemReallyThatBig.adoc
blog/2017-03-13-VisualizeTheScoreAndTheConstraints.adoc
index.html.haml
learn/useCases/index.html.haml
learn/useCases/schoolTimetabling.adoc

"School Timetabling" and "timetabling" in particular is an important SEO term. We do a it a lot, in many use cases, but hardly mention that keyword on our website.

School timetabling use case

---

_config/users.yml
community/branding.adoc

Add contributor

---

learn/video.adoc

Improve embedded playlist syntax

---

_config/pom.yml
learn/documentation.html.haml

Jira: https://issues.jboss.org/browse/PLANNER-1734

PLANNER-1734: Add optaweb-employee-rostering community docs

---

product/services.html.haml

Noticed this the other day and the link still redirects to the right page but this fixes the link text and updates the link.

Update BPM Suite to Process Automation Manager

---

_config/pom.yml
learn/documentation.html.haml

Jira: https://issues.redhat.com/browse/PLANNER-1741
Merge after: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1154

[PLANNER-1741] Add optaweb-vehicle-routing docs links

---

_layouts/releaseNotesBase.html.haml
code/license.adoc
community/droolsPlannerRenamed.adoc
download/download.html.haml
index.html.haml
learn/useCases/cloudOptimization.adoc
learn/useCases/conferenceScheduling.adoc
learn/useCases/employeeRostering.adoc
learn/useCases/maintenanceScheduling.adoc
learn/useCases/schoolTimetabling.adoc
learn/useCases/taskAssignmentOptimization.adoc
learn/useCases/vehicleRoutingProblem.adoc
localized/ja/index.adoc

http://www.apache.org/foundation/license-faq.html#License

Fix Apache License name

---

_config/pom.yml
download/download.html.haml

Jira: https://issues.redhat.com/browse/PLANNER-1778

Add download links for optaweb-vehicle-routing distribution zip

---

learn/documentation.html.haml

Jira: https://issues.redhat.com/browse/PLANNER-1741

Add links to optaweb-vehicle-routing docs

---

blog/2020-05-08-AIVersusCovid-19.adoc

remains feasible an employee -> remains feasible **when** an employee

Add missing word in blog post

---

download/upgradeRecipe/upgradeRecipe7.adoc

Also see https://github.com/kiegroup/optaplanner/pull/774

PLANNER-1579 Deprecate double-based score types

---

download/releaseNotes/releaseNotes7.adoc
download/upgradeRecipe/upgradeRecipe7.adoc

This completes the deprecation work.

PLANNER-1991 Another round of deprecations

---

download/upgradeRecipe/upgradeRecipe8.adoc

Addresses all backward-incompatible changes from:
https://github.com/triceo/optaplanner/pull/8
https://github.com/triceo/optaplanner/pull/13

PLANNER-2022 Document changes in solver configuration

---

download/upgradeRecipe/upgradeRecipe8.adoc

https://issues.redhat.com/browse/PLANNER-2050

PLANNER-2050 Reformat the upgrade recipe for 8

---

download/upgradeRecipe/upgradeRecipe8.adoc

Upgrade recipe for https://github.com/kiegroup/optaplanner/pull/838

PLANNER-2048 Remove xStreamAnnotatedClass

---

_config/users.yml
community/team.html.haml

A subset of the team changes - basically anything that does not require a new entry in users.yml

Update the team page

---

_config/users.yml

Adjusting Karina's gravatar ID on the contributors' page.

Updating contributors info with correct data

---

Gemfile
README.adoc

@triceo This also reverts some of the changes that you did earlier, which caused warning messages with me (and I believe Radovan and Jiri saw those showing up too with that change). However, I believe if you do a few `sudo gem pristine ... --version ...` commands on your machine, this will fix it. Would you mind pulling this PR locally and verifying that? I don't want to merge if we don't get it working on all our machines, including yours.

Upgrade json to fix CVE + Upgrade Awestruct

---

_config/users.yml
community/team.html.haml

according to @ge0ffrey proposal, here I am :wink:

emingora added to users.yml

---

learn/rhpds/index.adoc

I sometimes reference this page in chats, but I get the impression they often don't click through. This should fix that.

RHPDS overview page: make it more actionable, less inventory + motivate users to take action

---

xsd/optaplanner/optaplanner-8.xsd

Follow-up to https://github.com/kiegroup/optaplanner/pull/905

Remove KOptMoveSelector from XML config

---

download/upgradeRecipe/upgradeRecipe8.adoc

Merge these together:
* https://github.com/kiegroup/optaplanner/pull/928
* https://github.com/kiegroup/optaplanner-quickstarts/pull/3
* https://github.com/kiegroup/optaplanner-website/pull/279

Add generic type Score to SolverManager, SE, CMT, CM and Indictment

---

download/upgradeRecipe/upgradeRecipe8.adoc

https://github.com/kiegroup/optaplanner/pull/935

PLANNER-1362 Remove AbstractCustomPhaseCommand

---

build/update-versions.sh
update-versions.sh

This script is going to be called from the release pipeline to update the versions in links.

PLANNER-2217 Create a script that updates links

---

_partials/documentationJumbotron.html.haml

Link OptaPlanner Quickstarts repo

---

community/getHelp.html.haml
product/services.html.haml

Adjusting information regarding support for OptaPlanner.

Adjusting support info in getHelp and services pages

---

.awestruct_ignore
_ext/relative_template.atom.haml

Also adding vendor to the ignore file for generation

Fixing images in atom feed

---

blog/2021-03-04-OptimizingCovid19VaccinationScheduling.adoc

Updated the user selects and system automatically assigns headings to level 3 (===).

vaccination-blog-1-update - updated heading format

---

_config/pom.yml

This is the last step; once you review & merge, please announce the release.

Release OptaPlanner 8.3.0.Final

---

download/upgradeRecipe/upgradeRecipe8.adoc

Related https://github.com/kiegroup/optaplanner/pull/1258

Fail fast on null planning ID

---

assets/learn/slides/optaplanner-presentation/index.html
assets/learn/slides/optaplanner-presentation/training.html
content/code/sourceCode.adoc
content/localized/ja/UserGuide-chapter1.adoc

the user/pass issues fixed 5+ years ago

Git: Use https instead ssh

---

content/blog/2020/10/09/facilityLocationProblemClassDiagram.svg
content/learn/slides.adoc

This is also to test the auto publishing.

Fix broken link slides

---

build/rsync_website.sh

@yurloc @ge0ffrey IMPORTANT: before merging this PR:
1. disable [optaplanner_web_publshing_bake](https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/master/job/webs/job/optaplanner_web_publishing_bake/) 
2. enable [optaplanner-automatic-web-publishing](https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/master/job/webs/job/optaplanner-automatic-web-publishing/)
- a merge of this PR will trigger then [optaplanner-automatic-web-publishing](https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/master/job/webs/job/optaplanner-automatic-web-publishing/)
The job configuration was re factored so there was removed steps where keys were copied into the WORKSPACE.

refactored rsync script

---

pom.xml

Includes fix for: https://github.com/jbake-org/jbake/issues/708

Updated jbake-core to v2.7.0-rc.3

---

templates/base.ftl

ref https://github.com/kiegroup/drools-website/pull/166
ref https://github.com/kiegroup/jbpm-website/pull/173
local preview

Add footer link to Kogito

---

content/blog/2021/07/26/LetsOptaPlanYourJbpmTasksPart2.adoc

- relative links moved to absolute links due to broken links issue when the post is published in kie.org

PLANNER-2435: Kogito task assigning phase1 blog post

---

assets/robots.txt
content/learn/useCases/cloudOptimization.adoc
content/learn/useCases/conferenceScheduling.adoc
content/learn/useCases/employeeRostering.adoc
content/learn/useCases/maintenanceScheduling.adoc
content/learn/useCases/schoolTimetabling.adoc
content/learn/useCases/taskAssignmentOptimization.adoc
content/learn/useCases/vehicleRoutingProblem.adoc
data/videos.yml
templates/compatibilityBase.ftl
templates/macros.ftl
templates/useCaseBase.ftl

Automate landing pages tag adds relateded videos
Needed before @tarilabs copy pastes our structure for the drools website

Related videos automation

---

pom.xml

PLANNER-2506 Upgrade jbake to 2.7.0-rc.4 and fix the next button issue

---

templates/post.ftl

Fixes the broken links reported by SEO tools.

Fix 38 broken links for tags with spaces

---

assets/learn/slides/optaplanner-presentation/training.html
content/community/branding.adoc

Fix broken links to optaplanner-docs

---

content/compatibility/java.adoc
content/compatibility/python.adoc

Not yet linked from the frontpage.

Landing page: python

---

content/blog/2021/09/15/HowMuchFasterIsJava17.adoc
content/blog/2021/09/15/runBenchmarkJDKComparison.sh.txt

I decided to put it there, because this blog's shell script should not change over time. Each blog for a JDK release has it's own copy (= own version) of the script.

blog: Add shell script to reproduce the results

---

assets/website/optaplannerWebsite.js
templates/base.ftl
templates/compatibilityBase.ftl
templates/index.ftl
templates/macros.ftl
templates/useCaseBase.ftl

Use modal dialog for videos (no more adds) + video cards for related videos

---

assets/website/optaplannerWebsite.js
templates/base.ftl
templates/macros.ftl

Add title to the video modal

---

optaplanner-website-root/data/events.yml
optaplanner-website-root/templates/_content_community_eventsArchive.ftl
optaplanner-website-root/templates/macros.ftl

Requested by Matteo, but I was also thinking of this.
events.yml and and videos.yml should be consistent in their ordering.

events.yml order by date descending, just like videos.yml

---

optaplanner-website-root/pom.xml

@tarilabs This is the lazy fix :)

Update to Jbake 2.7.0-rc.5 to fix date issue

---

.github/workflows/main.yml
optaplanner-website-assembly/pom.xml
optaplanner-website-assembly/src/main/xsl/merge-sitemaps.xsl
optaplanner-website-docs/pom.xml

https://issues.redhat.com/browse/PLANNER-2585

PLANNER-2585 Optaplanner-website antora build fails on windows

---

optaplanner-website-root/content/blog/2018/05/23/BehindTheScenesOfRedHatSummitScheduling.adoc
optaplanner-website-root/content/blog/2018/07/03/AGiantLeapForwardWithMultithreadedIncrementalSolving.adoc
optaplanner-website-root/content/product/services.adoc

I missed these the first time going through the files.

Conscience language

---

optaplanner-website-root/content/community/branding.adoc
optaplanner-website-root/templates/index.ftl
optaplanner-website-root/templates/shared/footer.ftl

This is also going through legal.

Trademark guidelines

---

.ci/jenkins/Jenkinsfile.publish
.gitignore

**JIRA**: [BXMSPROD-1352](https://issues.redhat.com/browse/BXMSPROD-1352)
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1192
* https://github.com/kiegroup/kiegroup-website/pull/31
* https://github.com/kiegroup/optaplanner-website/pull/465
* https://github.com/kiegroup/drools-website/pull/199

BXMSPROD-1352: added Jenkinsfile for publishing website

---

optaplanner-website-root/content/compatibility/index.adoc
optaplanner-website-root/content/compatibility/kubernetes-openshift.adoc
optaplanner-website-root/templates/index.ftl

We can work out the landing page later, especially once a demo video is available.

Add landing page for Kubernetes OpenShift

---

optaplanner-website-root/content/learn/training.adoc

See https://kie.zulipchat.com/#narrow/stream/232679-optaplanner/topic/Training.20link.20-.20not.20found.

Update optaplanner course link

---

optaplanner-website-root/content/download/releaseNotes/releaseNotes8.adoc
optaplanner-website-root/content/download/upgradeRecipe/upgradeRecipe8.adoc

Relates to https://github.com/kiegroup/optaplanner/pull/1887.

PLANNER-2672 Return CompletableFuture for a problem change

---

.ci/jenkins/Jenkinsfile.publish
build/rsync_website.sh

the former filemgmt server is for rsync commands now filemgmt-prod-sync.jboss.org with port 2222

changed server name for publishing website

---

optaplanner-website-root/templates/compatibilityBase.ftl
optaplanner-website-root/templates/competitorBase.ftl
optaplanner-website-root/templates/index.ftl
optaplanner-website-root/templates/macros.ftl
optaplanner-website-root/templates/normalBase.ftl
optaplanner-website-root/templates/useCaseBase.ftl

Discussed with Phil/Ivo on what we want to do with this for now. They're in favor of temporarily disabling it.

Temporarily disable services offer

---

optaplanner-website-root/data/events.yml

Prime time presentation 
Community Central: Introduction to the OptaPlanner AI constraint solver
Description: Automate your business decisions in Java with Artificial Intelligence algorithms to improve your organization’s schedules, operations and processes. Optimize results. Find the best solution with hard and soft constraints. In this Community Central, Anna Dupliak will demonstrate OptaPlanner, an open source framework in Java that is easy to integrate with Quarkus, and that can automate these kinds of routines.

Community Central Upstream event

---

optaplanner-website-root/content/download/upgradeRecipe/upgradeRecipe7.adoc
optaplanner-website-root/content/download/upgradeRecipe/upgradeRecipe8.adoc

Remove extra `*` that makes file patterns bold

---

optaplanner-website-root/content/download/upgradeRecipe/upgradeRecipe8.adoc

https://issues.redhat.com/browse/PLANNER-2706
- https://github.com/kiegroup/optaplanner/pull/2213
- https://github.com/kiegroup/optaplanner-quickstarts/pull/414
- https://github.com/kiegroup/optaplanner-website/pull/539

PLANNER-2706 Upgrade to `@ShadowVariable`

---

optaplanner-website-root/pom.xml
pom.xml

Take advantages of the jbake upstream changes I did around Xmas.

Upgrade JBake to 2.7.0-rc.6 from 2.7.0-rc.5

---

.ci/jenkins/Jenkinsfile.publish
.ci/jenkins/dsl/jobs.groovy

to Kogito Pipelines framework ... as all other optaplanner jobs
https://issues.redhat.com/browse/PLANNER-2855
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/685
- https://github.com/kiegroup/optaplanner/pull/2301
- https://github.com/kiegroup/optaplanner-website/pull/547
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1360

[PLANNER-2855] Migrate optaplanner publish job

---

optaplanner-website-root/content/download/upgradeRecipe/upgradeRecipe8.adoc
optaplanner-website-root/data/pom.yml
optaplanner-website-root/templates/upgradeRecipeBase.ftl

Adding anchors to the versions to navigate it faster
Adding 7.13

Add TOC to migration guide and 7.13 mapping

---

.github/workflows/check_url.yml
.github/workflows/main.yml

https://issues.redhat.com/browse/BXMSPROD-1973
- https://github.com/kiegroup/kogito-pipelines/pull/868
- https://github.com/kiegroup/drools-website/pull/241
- https://github.com/kiegroup/kogito-runtimes/pull/2811
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/847
- https://github.com/kiegroup/optaplanner-website/pull/570

BXMSPROD-1973 Update GHA setup-java to v3

---

optaplanner-website-root/content/blog/2023/02/21/OptaPlanner-9-is-coming.adoc

Merge after the [8|9].35.0 release.

Simplify upgrade command with Beta2

---

optaplanner-website-root/content/download/upgradeRecipe/upgradeRecipe8.adoc

Merge together with
- https://github.com/kiegroup/optaplanner/pull/2642

PLANNER-2899 Upgrade instructions for list variable nearby selection

---

optaplanner-website-root/content/download/upgradeRecipe/upgradeRecipe8.adoc

Depends on https://github.com/kiegroup/optaplanner/pull/2701.

PLANNER-2911 Deprecate the *HibernateScoreTypes

---

.ci/jenkins/Jenkinsfile.publish

https://issues.redhat.com/browse/KOGITO-9275

KOGITO-9275 Jenkins: Switch jobs to use RHEL8
