kiegroup/optaplanner-website

- download/upgradeRecipe/upgradeRecipe6.4.adoc
The end of a code block is missing so the rest of the notes formatting is broken.
> Fix formatting in 6.4 upgrade recipe

- _ext/relative_template.atom.haml
- _partials/latestBlogPosts.html.haml
- blog/archive.html.haml
- blog/index.html.haml
Add the ability to have blogs ready but not visible from the landing page or the archive by adding `:awestruct-hidden: true` for these components.
> Don't show blog/entry if :awestruct-hidden is true

- download/releaseNotes/releaseNotes7.adoc
- download/upgradeRecipe/upgradeRecipe7.adoc
@ge0ffrey Review please.
Also, it would become much more convenient if N&N would become part of the documentation. Why?
- When I'm updating docs, it becomes trivial to update N&N in the same PR.
- Other projects have realized this as well, incl. [AssertJ ](https://assertj.github.io/doc/#release-notes) or our own [Drools](https://docs.drools.org/7.25.0.Final/drools-docs/html_single/#droolsreleasenoteschapter).
- That's where I'm looking for it.
> PLANNER-1599 N&N Sequential Subpillars

- community/branding.adoc
After updating docs to asciidoc, the logo link was broken. This PR fixes the logo reference.
> Fixing broken link for logo

- blog/2013-10-11-WillSkynetControlOurSchedule.adoc
- blog/2014-04-17-PutTheUserInControlOfTheScoreConstraints.adoc
- blog/2015-05-19-OptaPlannerOnAndroid.adoc
- blog/2015-10-01-SneakPeekAtOptaPlannerWorkbench.adoc
- blog/2015-12-01-TimeSchedulingDesignPatterns.adoc
- blog/2017-08-18-OptimizeYourProblemsUsingKieServerPart.adoc
- blog/2018-02-19-SchedulingVoxxedDaysZurich2018.adoc
- blog/2018-05-23-BehindTheScenesOfRedHatSummitScheduling.adoc
- blog/2018-08-21-UnitTestingConstraintsWithBusinessInputFromExcelOrLibreOffice.adoc
- blog/2019-05-09-RHSummit2019Part1.adoc
- blog/2019-05-09-RHSummit2019Part2.adoc
- blog/2019-05-09-RHSummit2019Part3.adoc
- download/releaseNotes/releaseNotes6.4.adoc
- download/releaseNotes/releaseNotes7.adoc
- learn/rhpds/optaweb-employee-rostering.adoc
- learn/rhpds/optaweb-vehicle-routing.adoc
- learn/useCases/cloudOptimization.adoc
- learn/useCases/conferenceScheduling.adoc
- learn/useCases/employeeRostering.adoc
- learn/useCases/maintenanceScheduling.adoc
- learn/useCases/schoolTimetabling.adoc
- learn/useCases/taskAssignmentOptimization.adoc
- learn/useCases/vehicleRoutingProblem.adoc
- learn/video.adoc
- website/optaplannerWebsite.css
Alternative to #172.
@ge0ffrey If you like this, I can apply the new syntax to all existing Youtube links. The advantage of the `video::` syntax is that you don't have to remember or copypaste the iframe code snippet with all required attributes. It's much simpler, produces the same result and you only need to the video ID.
> Apply max-width to all Youtube videos to avoid content wider that screen

- Rakefile.rb
- _dockerPublisher/Dockerfile
@ge0ffrey had to grant permissions to user jenkins since in fedora31 rake setup can done only as sudo user. Also the whole path to the _site had to be added for publishing correct.
I tested this locally and published to another server and it worked. So I am confident that this will work. If it doesn't we should revert this PR
> upgraded to fedora 31

- README.adoc
When doing `rake setup` Make is required, and Make does not come installed by default in Fedora 31 (that or I somehow uninstalled make)
> Add make to Fedora's dependencies

- _config/pom.yml
- download/download.html.haml
- learn/documentation.html.haml
Jira: https://issues.redhat.com/browse/PLANNER-1721
> [PLANNER-1721] Remove all Workbench references; they are now obsolete

- _config/pom.yml
- download/download.html.haml
- learn/documentation.html.haml
Jira: https://issues.redhat.com/browse/PLANNER-1748
EDIT: Good to merge. When 7.32.Final is released and download links are ready, I will create a PR that uncomments the download links to be published on the website.
> PLANNER-1748: Add optaweb-employee-rostering zip download links

- _config/pom.yml
Jira: https://issues.redhat.com/browse/PLANNER-1811
Merge with:
- https://github.com/kiegroup/optaweb-employee-rostering/pull/377
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1174
Note: The `optawebEmployeeRosteringDistributionZip` link needs to be updated with the new zip file name right before `7.33.0.Final` is released.
> [PLANNER-1811] Add optaweb prefix in employee rostering zip links

- _layouts/base.html.haml
- website/optaplannerWebsite.css
I couldn't get vertical-align to work for the github button (it doesn't have a class after DOM manipulation by github). In the end, removing the span and the form class improves whitespace, so the padding is worth the price.
> Add GitHub star button

- download/upgradeRecipe/upgradeRecipe8.adoc
Includes information from various sources:
- 7.x upgrade recipe. Deprecations were converted into removals.
- Revapi change logs.
- My own notes.
It seems shorter than it should be. It is not. 
Many of the changes we were doing had only small impact on public API.
> PLANNER-2010 Upgrade recipe for the 8.x API changes

- xsd/benchmark/benchmark-8.xsd
- xsd/benchmark/benchmark.xsd
- xsd/benchmark/index.html.haml
- xsd/optaplanner/optaplanner.xsd
- xsd/solver/index.html.haml
- xsd/solver/solver-8.xsd
- xsd/solver/solver.xsd
Splits the `optaplanner` XSD namespace into the `solver` and the `benchmark`.
Related PR:
https://github.com/kiegroup/optaplanner/pull/911
> Split solver and benchmark XSD namespaces

- _partials/downloadJumbotron.html.haml
- download/upgradeRecipe/upgradeRecipe8.adoc
- localized/ja/UserGuide-chapter1.adoc
JIRA:
https://issues.redhat.com/browse/PLANNER-2187
Relates to:
https://github.com/kiegroup/optaplanner/pull/950
https://github.com/kiegroup/optaplanner-quickstarts/pull/6
> PLANNER-2187 Use java 11 minimum for OptaPlanner 8

- _config/pom.yml
the links to 
https://repository.jboss.org/nexus/service/local/artifact/maven/redirect?r=snapshots&g=org.optaweb.employeerostering&a=optaweb-employee-rostering-distribution&v=7.45.0-SNAPSHOT&e=zip
and 
https://repository.jboss.org/nexus/service/local/artifact/maven/redirect?r=snapshots&g=org.optaweb.vehiclerouting&a=optaweb-vehicle-routing-distribution&v=7.45.0-SNAPSHOT&e=zip
are dead somehow - like there is nothing! Please check this.
> updated to 7.44.0.Final

- download/upgradeRecipe/upgradeRecipe8.adoc
Motivation: make the upgrade recipe look less scary :)
without making items minor that the average user would run into.
> SubPillars is for power users, so "minor" instead of "major"

- _config/pom.yml
- download/download.html.haml
- learn/documentation.html.haml
- xsd/benchmark/benchmark-8.xsd
- xsd/solver/solver-8.xsd
- removes links to KIE server and Drools
- updates OptaPlanner links to match the released 8.0.0.Beta1
- updates the XSDs
- optawebs stay on 7.45.0.Final so far
@mbiarnes would you please stop updating the optaplanner-website during the 7.x releases from now? The website will point to 8.x artifacts when we merge this PR.
> Release OptaPlanner 8.0.0.Beta1

- build/update-versions.sh
Enhances the regexp in update-version.sh to match also Beta and CR versions.
> Update version regexp should match also Beta and CR

- download/download.html.haml
I noticed the sections where used to be the Exec server on the Downloads page were still visible. This PR removes them completely.
> Remove the empty Exec server sections

- download/upgradeRecipe/upgradeRecipe8.adoc
Upgrade recipe for https://github.com/kiegroup/optaplanner/pull/1040 and the `SolverConfig.buildSolver()` removed earlier.
> Remove build methods from SolverConfig and PlannerBenchmarkConfig

- build/rsync_website.sh
@ge0ffrey Here is the new script that should be executed when optaplanner-webiste should be updated.
There is a Jenkins job [optaplanner_web_publishing_bake](https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/master/job/webs/job/optaplanner_web_publishing_bake/) which has to run manually. Once the decision was taken that it behaves properly we should change the jobs so it works with web-hooks, so they decide when this job runs and can change the name to `optaplanner_web_publishing`.
> Rsync test

- templates/macros.ftl
This is just a step along the way.
BEFORE
AFTER
The blue button now directly links to chapter 2 (quick start tutorials) in the user guide.
After the Antora work, that button can be adjusted further (see Karina's doc).
> Simplify the jumbotron callouts + add button for quickstarts repo

- content/download/upgradeRecipe/upgradeRecipe6.3.adoc
Literal monospace avoids having to escape individual characters.
See
https://docs.asciidoctor.org/asciidoc/latest/text/monospace/#literal-monospace.
This approach is already being used in `optaplanner-docs` so `consitency++`.
> Improve Move.toString() formatting

- content/blog/2020/05/05/WorkflowProcessesWithAIScheduling.adoc
The blog post is about a Quarkus based project. The tag makes the blog
post appear as a related post on the Quarkus compatibility page.
> Add quarkus tag to Workflow blog post

- assets/website/optaplannerWebsite.js
- templates/base.ftl
When an iframe's src changes, the browser seems to add its previous src
to the history.
As a result, if you play a couple of videos on a page you then have to
click "back" a number of times in order to get to the previous page.
To fix that, let's create a completely new iframe when showing a video.
> Prevent video iframe from adding to browser history

- optaplanner-website-docs/README.adoc
- optaplanner-website-docs/antora-playbook.yml
This configuration bypasses the cache located in (by default on Linux) ~/.cache/antora. Antora will always fetch source repositories.
> Always fetch antora source repos

- optaplanner-website-root/assets/code/.htaccess
- optaplanner-website-root/content/code/continuousIntegration.html
- optaplanner-website-root/content/code/issueTracker.html
- optaplanner-website-root/jbake.properties
- optaplanner-website-root/templates/redirectBase.ftl
GH pages does not support 301 redirects, or .htaccess files.
According to, meta refresh=0 are equally strong signals
https://developers.google.com/search/docs/advanced/crawling/301-redirects#metarefresh
This is a proof of concept for 2 of our old redirects. We still use some other .htaccess files, but if we're happy with this we can apply it there too.
> Redirect refresh=0 template (GitHub Pages friendly)

- optaplanner-website-root/content/learn/training.adoc
Removing katacoda information and adding link to an updated and self-paced exercise hosted on github. 
The previous courses are not provided in Katacoda anymore.
> Adjusting training broken links

- optaplanner-website-docs/package-lock.json
- optaplanner-website-docs/pom.xml
Latest node and npm were not available in
the cache, causing pipeline failures. Downgraded
to the latest available versions.
> Change node and npm to supported versions

- .github/workflows/check_url.yml
- .gitignore
**JIRA**: [BXMSPROD-1669](https://issues.redhat.com/browse/BXMSPROD-1669) 
Right after a release the versions have to be upgraded. In drools, jbpm and optaplanner the links in the web-page pointing to binaries to download from https://filemgmgt-prod.jboss.org/ are upgraded and have to be tested if they work.
> BXMSPROD-1669: added new git-hub-action for checking URLs of web page

- .github/workflows/check_url.yml
The versioning scheme has changed. 0.0.27 is now the latest. See https://github.com/urlstechie/urlchecker-action/issues/89.
> Update urlchecker-action to 0.0.27

- optaplanner-website-root/content/product/services.adoc
because they are in sustaining (no recent OptaPlanner versions)
> Remove RHDM and RHPAM references

- optaplanner-website-root/content/blog/2022/05/26/optaplanner-deprecates-score-drl.adoc
- optaplanner-website-root/content/download/releaseNotes/releaseNotes8.adoc
- optaplanner-website-root/content/download/upgradeRecipe/drl-to-constraint-streams-migration.adoc
- optaplanner-website-root/content/download/upgradeRecipe/index.adoc
- optaplanner-website-root/content/download/upgradeRecipe/upgradeRecipe8.adoc
- optaplanner-website-root/content/learn/drl-to-constraint-streams-migration.html
Motivation:
- Put the drl migration recipe, which is a long time upgrading recipe related artifact in the upgradeRecipes directory
- Make it easier to find the drl migration recipe by adding it in the "upgrade recipes" list. So it's clear it's one of the steps to do.
This has a huge fallout of changes, but so be it... Side-effects:
-  https://github.com/kiegroup/optaplanner/pull/2127
> Move drl migration guide into upgrade recipes

- .ci/jenkins/dsl/jobs.groovy
- .ci/jenkins/dsl/test.sh
https://issues.redhat.com/browse/PLANNER-2870
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/801
- https://github.com/kiegroup/optaplanner/pull/2550
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/842
- https://github.com/kiegroup/optaplanner-quickstarts/pull/505
- https://github.com/kiegroup/optaplanner-website/pull/569
- [9.x] https://github.com/kiegroup/optaplanner/pull/2558
> PLANNER-2870 Environments should be configurable via branch config

- optaplanner-website-docs/antora-playbook.yml
- optaplanner-website-root/data/pom.yml
Generated by build jenkins-KIE-optaplanner-8.34.x-release-optaplanner-post-release-1: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/8.34.x/job/release/job/optaplanner-post-release/1/
> Release OptaPlanner 8.34.0.Final

- optaplanner-website-docs/antora-playbook.yml
- optaplanner-website-root/content/xsd/benchmark/benchmark-8.xsd
- optaplanner-website-root/content/xsd/solver/solver-8.xsd
- optaplanner-website-root/data/pom.yml
Generated by build jenkins-KIE-optaplanner-8.35.x-release-optaplanner-post-release-1: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/8.35.x/job/release/job/optaplanner-post-release/1/
> Release OptaPlanner 8.35.0.Final

- optaplanner-website-docs/antora-playbook.yml
- optaplanner-website-root/data/pom.yml
Generated by build jenkins-KIE-optaplanner-8.36.x-release-optaplanner-post-release-1: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/8.36.x/job/release/job/optaplanner-post-release/1/
> Release OptaPlanner 8.36.0.Final

- optaplanner-website-root/templates/upgradeRecipeBase.ftl
LATEST points to 4.40.0, which is incompatible with the recipe. There is 4.44.0 already that works fine.
> Use the real latest rewrite plugin version

- optaplanner-website-root/content/xsd/benchmark/benchmark-8.xsd
- optaplanner-website-root/content/xsd/solver/solver-8.xsd
- optaplanner-website-root/data/pom.yml
Generated by build jenkins-KIE-optaplanner-8.38.x-release-optaplanner-post-release-3: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/8.38.x/job/release/job/optaplanner-post-release/3/
> Release OptaPlanner 8.38.0.Final

- optaplanner-website-root/templates/_content_download_download.ftl
The Downloads page will now provide links for the OptaPlanner 8 distribution as well.
> PLANNER-2922 Add distribution 8 to downloads

- optaplanner-website-root/data/pom.yml
Generated by build jenkins-KIE-optaplanner-8.40.x-release-optaplanner-post-release-1: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/8.40.x/job/release/job/optaplanner-post-release/1/
> Release OptaPlanner 8.40.0.Final

- optaplanner-website-root/data/pom.yml
Generated by build jenkins-KIE-optaplanner-8.41.x-release-optaplanner-post-release-1: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/8.41.x/job/release/job/optaplanner-post-release/1/
> Release OptaPlanner 8.41.0.Final

- optaplanner-website-root/data/pom.yml
Generated by build jenkins-KIE-optaplanner-8.42.x-release-optaplanner-post-release-1: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/8.42.x/job/release/job/optaplanner-post-release/1/
> Release OptaPlanner 8.42.0.Final

- optaplanner-website-root/data/pom.yml
Generated by build jenkins-KIE-optaplanner-8.43.x-release-optaplanner-post-release-1: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/8.43.x/job/release/job/optaplanner-post-release/1/
> Release OptaPlanner 8.43.0.Final

- optaplanner-website-root/data/pom.yml
Generated by build jenkins-KIE-optaplanner-8.44.x-release-optaplanner-post-release-1: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/8.44.x/job/release/job/optaplanner-post-release/1/
> Release OptaPlanner 8.44.0.Final
